#ifndef _APP_CONFIG_H_
#define _APP_CONFIG_H_

#define TASK_START_TASK_PRIORITY	( tskIDLE_PRIORITY + 1)


#define TASK_GP_TASK_PRIORITY		( tskIDLE_PRIORITY + 3 )
#define TASK_LCD_TASK_PRIORITY		( tskIDLE_PRIORITY + 2 )
//#define TASK_COM_TASK_PRIORITY		( tskIDLE_PRIORITY + 4 )
//#define TASK_LED_TASK_PRIORITY		( tskIDLE_PRIORITY + 5 )
#define TASK_ETH_INT_PRIORITY			tskIDLE_PRIORITY + 4
#define TASK_ETH_INT_STACK_SIZE			128



#endif
