#ifndef _APP_CONFIG_H_
#define _APP_CONFIG_H_

#define TASK_START_TASK_PRIORITY	( tskIDLE_PRIORITY + 1 )
#define TASK_ETH_INT_PRIORITY		( tskIDLE_PRIORITY + 2 )
#define TASK_LCD_TASK_PRIORITY		( tskIDLE_PRIORITY + 4 )
#define TASK_LWIP_PING_PRIORITY		( tskIDLE_PRIORITY + 5 )
#define TASK_LWIP_TCPIP_PRIORITY	( tskIDLE_PRIORITY + 6 )
#define TASK_NET_SERVER_PRIORITY	( tskIDLE_PRIORITY + 3 )


#define TASK_ETH_INT_STACK_SIZE					128
#define TASK_NET_SERVER_STACK_SIZE				128
#define TASK_LWIP_PING_STACKSIZE				512
#define TASK_LWIP_TCPIP_STACKSIZE				512


#endif
