/*! @file radio_config.h
 * @brief This file contains the automatically generated
 * configurations.
 *
 * @b COPYRIGHT
 * @n Silicon Laboratories Confidential
 * @n Copyright 2012 Silicon Laboratories, Inc.
 * @n http://www.silabs.com
 */

#ifndef RADIO_CONFIG_H_
#define RADIO_CONFIG_H_


// USER DEFINED PARAMETERS
//
// DEFINE CUSTOM PARAMETERS HERE!


// AUTOMATICALLY GENERATED CODE BELOW THIS LINE
//
// DO NOT EDIT/MODIFY BELOW!
// --------------------------------------------

// EZCONFIG ARRAY & CRC

#define RADIO_CONFIGURATION_DATA_EZCONFIG_ARRAY { \
0x81, 0x02, 0x1C, 0xDD, 0x44, 0x60, 0xD8, 0x90, 0x47, 0xFF, 0xB7, 0xA8, \
0x98, 0x3D, 0xD1, 0x29, 0x10, 0xAC, 0xA9, 0xAA, 0x9E, 0x8C, 0x20, 0x87, \
0x01, 0x8B, 0x90, 0xF6, 0xA6, 0xC6, 0x65, 0xE0, 0xE7, 0x13, 0xC9, 0x76, \
0x2E, 0xFD, 0xB6, 0xD3, 0xA6, 0x37, 0x41, 0x1B, 0xE8, 0xF5, 0xA9, 0x61, \
0x7B, 0x57, 0x18, 0x3F, 0x52, 0xD9, 0x09, 0xAF, 0xD4, 0xCE, 0x77, 0xD1, \
0x2A, 0x5E, 0x08, 0xF6, 0x3B, 0x5A, 0x9A, 0x44, 0x39, 0x52, 0x79, 0x5C, \
0x5E, 0x2F, 0x4A, 0x7A, 0xAC, 0xBF, 0x4C, 0x43, 0xD9, 0x51, 0x1A, 0x3D, \
0x66, 0xDB, 0x29, 0x86, 0x1A, 0x09, 0xE3, 0xDB, 0x87, 0x63, 0x94, 0x9E, \
0x84, 0xF7, 0x6F, 0x95, 0x3F, 0xD9, 0x72, 0x60, 0x96, 0xC0, 0xA2, 0xEE, \
0xD6, 0x1C, 0x77, 0x73, 0x0B, 0x17, 0x2C, 0x9F, 0x33, 0x85, 0x48, 0x2A, \
0xBA, 0x5D, 0x77, 0xA9, 0x48, 0x43, 0x2B, 0xF2, 0xB4, 0x16, 0x68, 0x4A, \
0x32, 0xF4, 0xBE, 0xFF, 0x5D, 0xF7, 0xB6, 0x01, 0x6C, 0x7C, 0x7B, 0xF6, \
0x29, 0xD2, 0x2F, 0xE1, 0xCF, 0x29, 0x76, 0x6C, 0x57, 0x5E, 0x16, 0x1A, \
0xDF, 0x99, 0xB0, 0x55, 0x93, 0xA9, 0x1B, 0xAD, 0x4A, 0x42, 0x1D, 0x6E, \
0xDB, 0xB0, 0x58, 0xDA, 0xFE, 0xD9, 0xF0, 0x50, 0x3D, 0x6F, 0xC2, 0x4D, \
0xD5, 0x5B, 0x06, 0x62, 0xA3, 0x88, 0xDE, 0x5B, 0xE6, 0x85, 0x62, 0xF2, \
0x92, 0x41, 0xCE, 0x8B, 0x69, 0x4B, 0xEB, 0x66, 0xD3, 0xBF, 0x4A, 0x86, \
0x7B, 0x59, 0x27, 0xA3, 0x8A, 0xF1, 0x78  }

#define RADIO_CONFIGURATION_DATA_EZCONFIG_ARRAY_CRC                      { 0xE712 }
#define RADIO_CONFIGURATION_DATA_RADIO_PACKET_LENGTH                     { 0x07 }
#define RADIO_CONFIGURATION_DATA_INT_CTL_ENABLE                          { 0x04 }
#define RADIO_CONFIGURATION_DATA_INT_CTL_PH_ENABLE                       { 0x00 }
#define RADIO_CONFIGURATION_DATA_INT_CTL_MODEM_ENABLE                    { 0x00 }
#define RADIO_CONFIGURATION_DATA_INT_CTL_CHIP_ENABLE                     { 0x04 }
#define RADIO_CONFIGURATION_DATA_RADIO_XO_FREQ                           { 30000000L }
#define RADIO_CONFIGURATION_DATA_EZCONFIG_XO_TUNE                        { 0x52 }



// DEFAULT VALUES FOR CONFIGURATION PARAMETERS

#define RADIO_CONFIGURATION_DATA_RADIO_BOOT_OPTIONS_DEFAULT                0x01
#define RADIO_CONFIGURATION_DATA_RADIO_XTAL_OPTIONS_DEFAULT                0x00
#define RADIO_CONFIGURATION_DATA_RADIO_XO_FREQ_DEFAULT                     30000000L

#define RADIO_CONFIGURATION_DATA_INT_CTL_ENABLE_DEFAULT                    0x04
#define RADIO_CONFIGURATION_DATA_INT_CTL_PH_ENABLE_DEFAULT                 0x00
#define RADIO_CONFIGURATION_DATA_INT_CTL_MODEM_ENABLE_DEFAULT              0x00
#define RADIO_CONFIGURATION_DATA_INT_CTL_CHIP_ENABLE_DEFAULT               0x04

#define RADIO_CONFIGURATION_DATA_FRR_CTL_A_MODE_DEFAULT                    0x08
#define RADIO_CONFIGURATION_DATA_FRR_CTL_B_MODE_DEFAULT                    0x06
#define RADIO_CONFIGURATION_DATA_FRR_CTL_C_MODE_DEFAULT                    0x04
#define RADIO_CONFIGURATION_DATA_FRR_CTL_D_MODE_DEFAULT                    0x0A

#define RADIO_CONFIGURATION_DATA_SYNC_BITS_31_24_DEFAULT                   0x2D
#define RADIO_CONFIGURATION_DATA_SYNC_BITS_23_16_DEFAULT                   0xD4

#define RADIO_CONFIGURATION_DATA_PA_PWR_LVL_DEFAULT                        0x7F

#define RADIO_CONFIGURATION_DATA_EZCONFIG_MODULATION_DEFAULT               0x02
#define RADIO_CONFIGURATION_DATA_EZCONFIG_XO_TUNE_DEFAULT                  0x40

#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_INTE_DEFAULT                 0x3C
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_2_DEFAULT               0x08
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_1_DEFAULT               0x00
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_0_DEFAULT               0x00
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT  0x00
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT  0x00

#define RADIO_CONFIGURATION_DATA_GPIO0_PIN_CFG_DEFAULT                     0x01
#define RADIO_CONFIGURATION_DATA_GPIO1_PIN_CFG_DEFAULT                     0x01
#define RADIO_CONFIGURATION_DATA_GPIO2_PIN_CFG_DEFAULT                     0x01
#define RADIO_CONFIGURATION_DATA_GPIO3_PIN_CFG_DEFAULT                     0x01
#define RADIO_CONFIGURATION_DATA_GPIO_NIRQ_MODE_DEFAULT                    0x00
#define RADIO_CONFIGURATION_DATA_GPIO_SDO_MODE_DEFAULT                     0x00
#define RADIO_CONFIGURATION_DATA_GPIO_GEN_CONFIG_DEFAULT                   0x00

#define RADIO_CONFIGURATION_DATA_CHANNEL_NUMBER_DEFAULT                    0x00

#define RADIO_CONFIGURATION_DATA_RADIO_PACKET_LENGTH_DEFAULT               0x10
#define RADIO_CONFIGURATION_DATA_RADIO_STATE_AFTER_POWER_UP_DEFAULT        0x01
#define RADIO_CONFIGURATION_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT       0x1000

#define RADIO_CONFIGURATION_DATA_RADIO_PATCH_INCLUDED                      0x00
#define RADIO_CONFIGURATION_DATA_RADIO_PATCH_SIZE                          0x00
#define RADIO_CONFIGURATION_DATA_RADIO_PATCH                               {  }

#ifndef RADIO_CONFIGURATION_DATA_EZCONFIG_ARRAY
#error "This property must be defined!"
#endif

#ifndef RADIO_CONFIGURATION_DATA_EZCONFIG_ARRAY_CRC
#error "This property must be defined!"
#endif

#ifndef RADIO_CONFIGURATION_DATA_RADIO_BOOT_OPTIONS
#define RADIO_CONFIGURATION_DATA_RADIO_BOOT_OPTIONS    { RADIO_CONFIGURATION_DATA_RADIO_BOOT_OPTIONS_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_RADIO_XTAL_OPTIONS
#define RADIO_CONFIGURATION_DATA_RADIO_XTAL_OPTIONS    { RADIO_CONFIGURATION_DATA_RADIO_XTAL_OPTIONS_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_RADIO_XO_FREQ
#define RADIO_CONFIGURATION_DATA_RADIO_XO_FREQ         { RADIO_CONFIGURATION_DATA_RADIO_XO_FREQ_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_INT_CTL_ENABLE
#define RADIO_CONFIGURATION_DATA_INT_CTL_ENABLE        { RADIO_CONFIGURATION_DATA_INT_CTL_ENABLE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_INT_CTL_PH_ENABLE
#define RADIO_CONFIGURATION_DATA_INT_CTL_PH_ENABLE     { RADIO_CONFIGURATION_DATA_INT_CTL_PH_ENABLE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_INT_CTL_MODEM_ENABLE
#define RADIO_CONFIGURATION_DATA_INT_CTL_MODEM_ENABLE  { RADIO_CONFIGURATION_DATA_INT_CTL_MODEM_ENABLE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_INT_CTL_CHIP_ENABLE
#define RADIO_CONFIGURATION_DATA_INT_CTL_CHIP_ENABLE   { RADIO_CONFIGURATION_DATA_INT_CTL_CHIP_ENABLE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FRR_CTL_A_MODE
#define RADIO_CONFIGURATION_DATA_FRR_CTL_A_MODE        { RADIO_CONFIGURATION_DATA_FRR_CTL_A_MODE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FRR_CTL_B_MODE
#define RADIO_CONFIGURATION_DATA_FRR_CTL_B_MODE        { RADIO_CONFIGURATION_DATA_FRR_CTL_B_MODE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FRR_CTL_C_MODE
#define RADIO_CONFIGURATION_DATA_FRR_CTL_C_MODE        { RADIO_CONFIGURATION_DATA_FRR_CTL_C_MODE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FRR_CTL_D_MODE
#define RADIO_CONFIGURATION_DATA_FRR_CTL_D_MODE        { RADIO_CONFIGURATION_DATA_FRR_CTL_D_MODE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_SYNC_BITS_31_24
#define RADIO_CONFIGURATION_DATA_SYNC_BITS_31_24       { RADIO_CONFIGURATION_DATA_SYNC_BITS_31_24_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_SYNC_BITS_23_16
#define RADIO_CONFIGURATION_DATA_SYNC_BITS_23_16       { RADIO_CONFIGURATION_DATA_SYNC_BITS_23_16_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_PA_PWR_LVL
#define RADIO_CONFIGURATION_DATA_PA_PWR_LVL            { RADIO_CONFIGURATION_DATA_PA_PWR_LVL_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_EZCONFIG_MODULATION
#define RADIO_CONFIGURATION_DATA_EZCONFIG_MODULATION   { RADIO_CONFIGURATION_DATA_EZCONFIG_MODULATION_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_EZCONFIG_XO_TUNE
#define RADIO_CONFIGURATION_DATA_EZCONFIG_XO_TUNE      { RADIO_CONFIGURATION_DATA_EZCONFIG_XO_TUNE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FREQ_CONTROL_INTE
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_INTE     { RADIO_CONFIGURATION_DATA_FREQ_CONTROL_INTE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_2
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_2   { RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_2_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_1
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_1   { RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_1_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_0
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_0   { RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_0_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1  { RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0
#define RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0  {  RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_GPIO0_PIN_CFG
#define RADIO_CONFIGURATION_DATA_GPIO0_PIN_CFG         { RADIO_CONFIGURATION_DATA_GPIO0_PIN_CFG_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_GPIO1_PIN_CFG
#define RADIO_CONFIGURATION_DATA_GPIO1_PIN_CFG         { RADIO_CONFIGURATION_DATA_GPIO1_PIN_CFG_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_GPIO2_PIN_CFG
#define RADIO_CONFIGURATION_DATA_GPIO2_PIN_CFG         { RADIO_CONFIGURATION_DATA_GPIO2_PIN_CFG_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_GPIO3_PIN_CFG
#define RADIO_CONFIGURATION_DATA_GPIO3_PIN_CFG         { RADIO_CONFIGURATION_DATA_GPIO3_PIN_CFG_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_GPIO_NIRQ_MODE
#define RADIO_CONFIGURATION_DATA_GPIO_NIRQ_MODE        { RADIO_CONFIGURATION_DATA_GPIO_NIRQ_MODE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_GPIO_SDO_MODE
#define RADIO_CONFIGURATION_DATA_GPIO_SDO_MODE         { RADIO_CONFIGURATION_DATA_GPIO_SDO_MODE_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_GPIO_GEN_CONFIG
#define RADIO_CONFIGURATION_DATA_GPIO_GEN_CONFIG       { RADIO_CONFIGURATION_DATA_GPIO_GEN_CONFIG_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_CHANNEL_NUMBER
#define RADIO_CONFIGURATION_DATA_CHANNEL_NUMBER        { RADIO_CONFIGURATION_DATA_CHANNEL_NUMBER_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_RADIO_PACKET_LENGTH
#define RADIO_CONFIGURATION_DATA_RADIO_PACKET_LENGTH   { RADIO_CONFIGURATION_DATA_RADIO_PACKET_LENGTH_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_RADIO_STATE_AFTER_POWER_UP
#define RADIO_CONFIGURATION_DATA_RADIO_STATE_AFTER_POWER_UP  { RADIO_CONFIGURATION_DATA_RADIO_STATE_AFTER_POWER_UP_DEFAULT }
#endif

#ifndef RADIO_CONFIGURATION_DATA_RADIO_DELAY_CNT_AFTER_RESET
#define RADIO_CONFIGURATION_DATA_RADIO_DELAY_CNT_AFTER_RESET { RADIO_CONFIGURATION_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT }
#endif

#define RADIO_CONFIGURATION_DATA { \
                            RADIO_CONFIGURATION_DATA_EZCONFIG_ARRAY,                   \
                            RADIO_CONFIGURATION_DATA_EZCONFIG_ARRAY_CRC,               \
                            RADIO_CONFIGURATION_DATA_RADIO_BOOT_OPTIONS,               \
                            RADIO_CONFIGURATION_DATA_RADIO_XTAL_OPTIONS,               \
                            RADIO_CONFIGURATION_DATA_RADIO_XO_FREQ,                    \
                            RADIO_CONFIGURATION_DATA_INT_CTL_ENABLE,                   \
                            RADIO_CONFIGURATION_DATA_INT_CTL_PH_ENABLE,                \
                            RADIO_CONFIGURATION_DATA_INT_CTL_MODEM_ENABLE,             \
                            RADIO_CONFIGURATION_DATA_INT_CTL_CHIP_ENABLE,              \
                            RADIO_CONFIGURATION_DATA_FRR_CTL_A_MODE,                   \
                            RADIO_CONFIGURATION_DATA_FRR_CTL_B_MODE,                   \
                            RADIO_CONFIGURATION_DATA_FRR_CTL_C_MODE,                   \
                            RADIO_CONFIGURATION_DATA_FRR_CTL_D_MODE,                   \
                            RADIO_CONFIGURATION_DATA_SYNC_BITS_31_24,                  \
                            RADIO_CONFIGURATION_DATA_SYNC_BITS_23_16,                  \
                            RADIO_CONFIGURATION_DATA_PA_PWR_LVL,                       \
                            RADIO_CONFIGURATION_DATA_EZCONFIG_MODULATION,              \
                            RADIO_CONFIGURATION_DATA_EZCONFIG_XO_TUNE,                 \
                            RADIO_CONFIGURATION_DATA_FREQ_CONTROL_INTE,                \
                            RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_2,              \
                            RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_1,              \
                            RADIO_CONFIGURATION_DATA_FREQ_CONTROL_FRAC_0,              \
                            RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1, \
                            RADIO_CONFIGURATION_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0, \
                            RADIO_CONFIGURATION_DATA_GPIO0_PIN_CFG,                    \
                            RADIO_CONFIGURATION_DATA_GPIO1_PIN_CFG,                    \
                            RADIO_CONFIGURATION_DATA_GPIO2_PIN_CFG,                    \
                            RADIO_CONFIGURATION_DATA_GPIO3_PIN_CFG,                    \
                            RADIO_CONFIGURATION_DATA_GPIO_NIRQ_MODE,                   \
                            RADIO_CONFIGURATION_DATA_GPIO_SDO_MODE,                    \
                            RADIO_CONFIGURATION_DATA_GPIO_GEN_CONFIG,                  \
                            RADIO_CONFIGURATION_DATA_CHANNEL_NUMBER,                   \
                            RADIO_CONFIGURATION_DATA_RADIO_PACKET_LENGTH,              \
                            RADIO_CONFIGURATION_DATA_RADIO_STATE_AFTER_POWER_UP,       \
                            RADIO_CONFIGURATION_DATA_RADIO_DELAY_CNT_AFTER_RESET       \
                            }


#endif /* RADIO_CONFIG_H_ */